#### 1. EMail Generator
* Write a function to take First Name, Last Name and Date of Birth as input from the user and generate an EMail ID for them.
* The function should return the email id as <br>First two letters of First Name,<br>followed by First letter of Last Name,<br>followed by DOB without '/' followed by '@xyz.com'
* For Eg: **First Name:** Alice , **Last Name:** Garner , **DOB:** 07/11/1995
* Eg Output: alg07111995@xyz.com

In [3]:
email = ""

def get():
    a = input('Enter Your First Name : ')
    b = input('Enter Your Last Name : ')
    c = input('Enter DOB DD/MM/YYYY : ')
    fn = a[0].lower()+a[1].lower()
    ln = b[0].lower()
    dob = c.split('/')
    email = fn,ln,dob[0],dob[1],dob[2],"@xyz.com"
    e = ""
    for i in range(len(email)):
        e += email[i]
    print(e)
get()


Enter Your First Name : Hitesh
Enter Your Last Name : Kale
Enter DOB DD/MM/YYYY : 08/01/1996
hik08011996@xyz.com


#### 2. Brightness Adjustments

* Intuition: Let us say you have a grayscale image matrix of dimension 3x3<br>[150, 23, 21]<br>[168, 145, 23]<br>[170, 163, 150]<br>we need to reduce the brightness of this image by a factor of 10 i.e. each element of the image matrix should be subtracted by 10. Thus giving us the output image matrix as <br>[140, 13, 11]<br>[158, 135, 13]<br>[160, 153, 140]
* Create a 3x3 matrix having random values between the range of 0 to 255.
* Create a 3x3 matrix having all elements as 10.
* Reduce (Subtraction) the brightness matrix from the image matrix.

In [4]:
import numpy as np

print("Random value matrix between 0 to 255 : ")
a = np.random.randint(0, 255, (3,3))
print(a)

print("Matrix with all element as 10 : ")
b = np.full((3, 3), 10)
print(b)

# c = np.subtract(a,b)
c = a - b
print("Ans : ")
print(c)

Random value matrix between 0 to 255 : 
[[ 28  31 197]
 [227  26 159]
 [ 56  58 247]]
Matrix with all element as 10 : 
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Ans : 
[[ 18  21 187]
 [217  16 149]
 [ 46  48 237]]


#### 3. Central Tendency Test

* Intuition: Our goal here is to check the skewness of our distribution.
* Skewness
    * Positively Skewed : Mean > Median
    * Negetively Skewed : Mean < Median
    * Normal Curve : Mean = Median
* Write a function that takes an array of 9 numbers as input and returns the skewness of its distribution.
* Try your function for these inputs
    * Input: [1,2,3,4,5,6,7,8,9] , Expected Output: "Normal Curve"
    * Input: [1,2,3,4,5,6,9,9,10] , Expected Output: "Positively Skewed"
    * Input: [1,1,1,4,5,6,7,8,9] , Expected Output: "Negatively Skewed"
* **Note:** For this test consider the distribution to be sorted in an ascending order. Write code in such a way that even if unsorted array is passed as an input it handles it correctly.

In [12]:
l1 = []
for i in range(9):
    x = int(input("Enter no : "))
    l1.append(x)
l1.sort()
print(l1)
m1 = 0
for i in range(len(l1)):
    m1 = m1 + l1[i]
mean = m1/len(l1)
median = l1[4]

if mean > median:
    print("Positively Skewed")
elif mean < median:
    print("Negetively Skewed")
else:
    print("Normal Curve")
    

Enter no : 1
Enter no : 2
Enter no : 3
Enter no : 4
Enter no : 5
Enter no : 6
Enter no : 9
Enter no : 9
Enter no : 10
[1, 2, 3, 4, 5, 6, 9, 9, 10]
Positively Skewed


#### 4. Calculating Distances

* Below are two equations for calculating distances between 2 points
    * Euclidean Distance : $\sqrt{(x2 - x1)^2 + (y2-y1)^2}$
    * Manhattan Distance : $ |x2-x1| + |y2-y1| $
* Write a function that takes the x and y coordiantes for two points as inputs and returns the Euclidean and Manhattan distance between the two.

In [5]:
import math

def get():
    print("Enter x co-ordinate : ")
    x = []
    for i in range(2):
        a = int(input('Enter nos : '))
        x.append(a)
    print("Enter y co-ordinate : ")
    y = []
    for i in range(2):
        a = int(input('Enter nos : '))
        y.append(a)
    ED = math.sqrt(math.pow(x[1]-x[0], 2) + math.pow(y[1]- y[0], 2) * 1.0)
    MD = abs(x[1] - x[0]) + abs(y[1] - y[0])
    return ED,MD
l1 = get()
print("Euclidean Distance",l1[0])
print("Manhattan Distance",l1[1])


Enter x co-ordinate : 
Enter nos : 3
Enter nos : 4
Enter y co-ordinate : 
Enter nos : 4
Enter nos : 3
Euclidean Distance 1.4142135623730951
Manhattan Distance 2


#### 5. Softmax Function

* The Softmax Function : $ \frac{e^x}{\sum{e^x}} $
* Create a function that takes a array of numbers as input and returns the probabilities of each element of that array.
* Eg: 
    * Input : [1,2,3]
    * Denominator : e^1 + e^2 + e^3 = 2.71 + 7.38 + 20.08 = 30.16
    * Softmax for each element:
        * e^1/30.16 = 0.089
        * e^2/30.16 = 0.244
        * e^3/30.16 = 0.665

In [13]:
import numpy as np

def softmaxF(l1):
    a = np.exp(l1)
    b = np.sum(a)
    c = np.divide(a,b)
    return c
    
#     print(a)
#     print(b)
#     print(np.sum(a))

l1 = []
for i in range(3):
    x = int(input('Enter no : '))
    l1.append(x)
print("Probability of each element is", softmaxF(l1))
print(np.sum(softmaxF(l1)))

Enter no : 1
Enter no : 2
Enter no : 3
Probability of each element is [0.09003057 0.24472847 0.66524096]
1.0
