In [35]:
import numpy as np

x = np.random.randint(1,50, (6,6))
print(x)

[[43 20 42 24 42 12]
 [42 26 33 15 22 31]
 [41 19  9 12 29 27]
 [ 2 20 49 34 13 27]
 [37 24 47 17  4 43]
 [ 1 39 18 16 49 34]]


In [23]:
np.sort(x, axis=0)

array([[ 2,  2,  4,  3,  3],
       [ 9,  9,  6,  5,  5],
       [12, 12,  8, 12, 11],
       [16, 18, 12, 15, 13],
       [18, 19, 16, 19, 18]])

In [24]:
np.sort(x, axis=1)

array([[ 5,  8, 11, 12, 19],
       [ 5,  6,  9, 18, 19],
       [ 2,  2, 12, 13, 15],
       [ 3,  4, 12, 16, 18],
       [ 3,  9, 12, 16, 18]])

In [25]:
a = np.array([5,1,7,6,2,8,9,5])
np.argsort(a)

array([1, 4, 0, 7, 3, 2, 5, 6], dtype=int64)

In [15]:
np.sort(a)

array([1, 2, 5, 5, 6, 7, 8, 9])

In [14]:
np.partition(a, 4)

array([1, 5, 2, 5, 6, 7, 9, 8])

In [38]:
print(x)

print("\n\n",np.partition(x, 3, axis=0))

[[43 20 42 24 42 12]
 [42 26 33 15 22 31]
 [41 19  9 12 29 27]
 [ 2 20 49 34 13 27]
 [37 24 47 17  4 43]
 [ 1 39 18 16 49 34]]


 [[ 2 20  9 15  4 27]
 [ 1 19 18 12 13 12]
 [37 20 33 16 22 27]
 [41 24 42 17 29 31]
 [42 26 47 24 42 34]
 [43 39 49 34 49 43]]
